name: C#
on:
  push:
  pull_request:
jobs:
  windows-latest:
    runs-on: 'windows-latest'
    defaults:
      run:
        working-directory: ./CSharp
    steps:
    - uses: actions/checkout@v2
    - name: Copy Clipper2Lib to USINGZ directory
      run: cp Clipper2Lib/*.cs USINGZ/
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.x'    
    - name: Install Dependencies
      run: dotnet restore
    - name: Build Solution
      run: dotnet build --configuration Release --no-restore
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
